# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c563cda80cd098e2e41fbe0ae660d55214562ba4db3c431113d21146dbc29fea29f50a6c46896e69a68a45aab7e2194f363e1afb2d308ad7bc4f083a035664d3

test:
  secret_key_base: 5b207b9ac9056a40f6ae9b289fe41887c91ed60d51dc36ce391c2fcc6674c41a8257450a6eb4c3f9eb85d00d426693655d4075a90242a483943c25f0729ee4ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
